# Generated by Django 6.0.1 on 2026-01-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_budget_month_alter_budget_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.AddField(
            model_name='income',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
