# Generated by Django 6.0.1 on 2026-01-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_income_description_income_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
